Support rem

diff --git a/acu b/acu
--- a/acu
+++ b/acu
@@ -19,7 +19,7 @@ utilname="Arch (ARM) Configuration Utility"
 # utilver
 # this value is updated for release (acu compares this value with the remote one to determine whether an update is available)
 # format of Version Number is YYMMDDNN which NN is 1-99 count on updates commited on the same day
-utilver=24022310
+utilver=24022401
 
 # branch
 # currently, there are two branch/channel which is main and dev
@@ -55,6 +55,9 @@ adrepo_url="https://api.github.com/repos/kwankiu/archlinux-installer-rock5/relea
 
 # directory for storing source files
 source_repo_dir="source-repo-dir"
+
+# repo list
+repositories_file="/usr/lib/acu/config/repo.yaml"
 
 ################################################################
 # Tools for formatting / styling
@@ -257,6 +260,145 @@ install_pkg_from_url() {
         sudo pacman -U --overwrite \* $ipkgname --noconfirm
     fi
     rm -rf $ipkgname
+}
+
+# Function to add a repository item to the YAML file
+add_repository() {
+    # Check if YAML file exists
+    if [ ! -f "$repositories_file" ]; then
+        # Create folder if it doesn't exist already
+        sudo mkdir -p "$(dirname "$repositories_file")"
+        echo "repositories:" > "$repositories_file"
+    fi
+    # Read repository name
+    if [ -z "$1" ]; then
+        read -p "Enter repository name: " repo_name
+    else
+        repo_name="$1"
+    fi
+
+    # Read repository URL
+    if [ -z "$2" ]; then
+    read -p "Enter repository URL: " repo_url
+    else
+        repo_url="$2"
+    fi
+
+    # Validate and auto-detect repository type based on URL format
+    if [[ "$repo_url" == "https://api.github.com/orgs"* ]]; then
+        repo_type="ghapi-orgs"
+    elif [[ "$repo_url" == "https://api.github.com/repos"* ]]; then
+        repo_type="ghapi-releases"
+    elif [[ "$repo_url" == "http://"*"/"*"/"* || "$repo_url" == "https://"*"/"*"/"* ]]; then
+        repo_type="agr"
+    elif [[ "$repo_url" == "http://"* || "$repo_url" == "https://"* ]]; then
+        repo_type="git"
+    else
+        echo "Invalid repository URL format."
+        return
+    fi
+
+    # Append new repository item to YAML file
+    echo "- repo_name: $repo_name" >> "$repositories_file"
+    echo "  repo_type: $repo_type" >> "$repositories_file"
+    echo "  repo_url: $repo_url" >> "$repositories_file"
+
+    echo "Repository added successfully."
+}
+
+# Function to load repositories into arrays
+load_repositories() {
+    # Initialize arrays for storing repository information
+    repo_names=()
+    repo_types=()
+    repo_urls=()
+
+    # Read repositories from YAML file
+    while IFS= read -r line; do
+        if [[ $line == *"repo_name"* ]]; then
+            repo_name=$(echo "$line" | awk '{print $3}')
+            repo_names+=("$repo_name")
+        elif [[ $line == *"repo_type"* ]]; then
+            repo_type=$(echo "$line" | awk '{print $2}')
+            repo_types+=("$repo_type")
+        elif [[ $line == *"repo_url"* ]]; then
+            repo_url=$(echo "$line" | awk '{print $2}')
+            repo_urls+=("$repo_url")
+        fi
+    done < "$repositories_file"
+}
+
+# Function to list repositories sorted by type
+list_repositories() {
+    load_repositories
+
+    # Print repositories
+    echo "List of Repositories:"
+    for ((i = 0; i < ${#repo_names[@]}; i++)); do
+        echo "  Name: ${repo_names[i]}"
+        echo "  Type: ${repo_types[i]}"
+        echo "  URL: ${repo_urls[i]}"
+    done
+}
+
+# Function to fetch packages of a repositories
+fetch_repositories() {
+    load_repositories
+    echo ":: Fetching package repositories..."
+
+    for ((i = 0; i < ${#repo_names[@]}; i++)); do
+        echo -n "${repo_names[i]}"
+        printf "\t\t [ ########################## ] \t"
+        case ${repo_types[i]} in
+            agr)
+                agr rem set ${repo_names[i]} ${repo_urls[i]}.git
+                agr
+                ;;
+            ghapi-orgs)
+                echo
+                echo -e "n" | get_ghapi_orgs ${repo_urls[i]}
+                ;;
+            ghapi-releases)
+                adrepo_url=${repo_urls[i]}
+                echo
+                echo -e "n" | install_ghrel_packages .pkg.tar. | grep .pkg.tar.*
+                ;;
+            git)
+                if curl -s --head ${repo_urls[i]} &> /dev/null; then
+                    echo "${repo_urls[i]}: returns OK"
+                else
+                    echo "Failed to resolve: ${repo_urls[i]}"
+                fi
+                ;;
+            *)
+                echo "Invalid repository type. Valid types are: agr, ghapi-orgs, ghapi-releases, git."
+                return
+                ;;
+        esac
+
+    done
+}
+
+# Get available repo of GitHub Organizations
+get_ghapi_orgs() {
+    if [ -z "$1" ]; then
+        colorecho "$RED" "Error: No url specified."
+        exit 1
+    else
+        apiurl=$1
+    fi
+    
+    ghrel_url=("$apiurl")
+    dgpkg_list=()
+
+    for which_url in "${ghrel_url[@]}"; do
+      dgpkg_list+=($(curl -s "${which_url}?per_page=100" | grep -oP '"full_name": "(?!.*/\.)\K[^"]+'))
+    done
+
+    for url in "${dgpkg_list[@]}"; do
+        selection=$(basename "$url")
+        echo "$selection"
+    done
 }
 
 # Download Packages from a GitHub Release Repo
@@ -1630,6 +1772,15 @@ elif [ "$1" = "downgrade" ] || [ "$1" = "-D" ]; then
     downgrade_packages "$2" "$3"
 
 elif [ "$1" = "rem" ]; then
+    if [ -z "$2" ]; then
+        fetch_repositories
+    elif [ "$2" = "list" ]; then
+        list_repositories
+    elif [ "$2" = "set" ]; then
+        add_repository "$3" "$4"
+    fi
+
+elif [ "$1" = "add-repo" ]; then
     add_repo "$2" "$3" "$4"
 
 ### Features - System Maintenance ###
